global:
  scrape_interval: 15s # How often to scrape targets

scrape_configs:
  - job_name: 'backend-metrics'
    static_configs:
      - targets: ['backend:8000'] # Replace with actual backend service address

  - job_name: 'web3-metrics'
    static_configs:
      - targets: ['web3-node:8545'] # Web3 node metrics

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] # System-level monitoring
